[package]
name = "section3"
version = "1.0.0"
authors = []

[addresses]
std = "0x1"
section3 = "0x111"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
